name: qr_scanner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mobile_scanner: ^5.1.1
  pretty_qr_code: ^3.3.0

  path: ^1.9.0
  path_provider: ^2.1.3
  image_picker: ^1.1.1
  url_launcher: ^6.2.6
flutter:
  uses-material-design: true
